"""Build paste-ready bundles from the modular source.

Produces:
  dist/Code.gs       — all .gs concatenated (use with dist/Index.html, e.g. via clasp)
  dist/Index.html    — the UI with CSS+JS inlined
  dist/Standalone.gs — EVERYTHING in one file (code + page); paste this single file into the
                       default Code.gs of a new Apps Script project. No separate HTML file.
  demo.html          — standalone local preview (mock backend, no deploy)

The modular files in this folder are the source of truth; edit those, then run:
    python build.py
"""
import io, os, json

def read(p):
    return io.open(p, encoding="utf-8").read()

GS_ORDER = ["Config.gs", "Setup.gs", "Docx.gs", "RefParser.gs", "NameSplit.gs", "SheetIO.gs", "Code.gs"]
os.makedirs("dist", exist_ok=True)

# --- combined .gs ---
parts = ["// ===== ACADIA Reference Indexer — combined build. Edit the modular .gs files, re-run build.py. =====\n"]
for f in GS_ORDER:
    parts.append("\n// ---------- " + f + " ----------\n")
    parts.append(read(f))
combined_gs = "\n".join(parts)
io.open("dist/Code.gs", "w", encoding="utf-8").write(combined_gs)

# --- inlined Index.html (resolves the Apps Script include() calls) ---
index = (read("Index.html")
         .replace("<?!= include('Stylesheet'); ?>", read("Stylesheet.html"))
         .replace("<?!= include('JavaScript'); ?>", read("JavaScript.html")))
io.open("dist/Index.html", "w", encoding="utf-8").write(index)

# --- single-file standalone: combined .gs + the page inlined + a doGet that serves it ---
# Appended doGet overrides the one in Code.gs (last declaration wins), so the editor pastes
# ONE file and never has to create a separate HTML file.
standalone = (combined_gs
    + "\n\n// ---------- standalone page (overrides doGet; no separate HTML file needed) ----------\n"
    + "var STANDALONE_PAGE_HTML = " + json.dumps(index) + ";\n"
    + "function doGet() {\n"
    + "  return HtmlService.createHtmlOutput(STANDALONE_PAGE_HTML)\n"
    + "    .setTitle('ACADIA 2026 Reference Indexer')\n"
    + "    .addMetaTag('viewport', 'width=device-width, initial-scale=1');\n"
    + "}\n")
io.open("dist/Standalone.gs", "w", encoding="utf-8").write(standalone)

# --- local preview (client falls back to mock backend) ---
banner = ("<!-- GENERATED by build.py — standalone preview, mock backend (no Drive/Sheets). "
          "Edit Index/Stylesheet/JavaScript.html, not this file. -->\n")
io.open("demo.html", "w", encoding="utf-8").write(banner + index)

print("built dist/Code.gs, dist/Index.html, dist/Standalone.gs, demo.html")
